name: Deploy to Azure Container Registry (ACR) and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Azure Login using Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Store service principal credentials as a secret

      # Login to Azure Container Registry (ACR)
      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --no-cache -t zet-wallet:latest .

      # Tag the image for ACR
      - name: Tag Docker image
        run: |
          docker tag zet-wallet:latest ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_REPOSITORY }}:latest

      # Push the image to ACR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_REPOSITORY }}:latest