name: Deploy to Elastic Container Registry (ECR)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ECR Login using AWS CLI
      - name: ECR Login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }} # Store service principal credentials as a secret
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Store service principal credentials as a secret
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Login to Elastic Container Registry (ECR)
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --no-cache -t zet-wallet:latest .

      # Tag the image for ECR
      - name: Tag Docker image
        run: |
          docker tag zet-wallet:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_REPOSITORY }}:latest

      # Push the image to ECR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_REPOSITORY }}:latest